default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/hihelloreid_development

test:
  <<: *default
  database: db/hihelloreid_test

production:
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

#:development:
#  adapter: sqlite3
#  database: db/hihelloreid_development.sqlite3
#  pool: 5
#  timeout: 5000

#production:
#  adapter: postgresql
#  encoding: unicode
#  pool: 5
#  host: <%= ENV['DATABASE_HOST'] %>
#  database: <%= ENV['DATABASE_NAME'] %>
#  username: <%= ENV['DATABASE_USER'] %>
#  password: <%= ENV['DATABASE_PASSWORD'] %>
